import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from 'next-themes'
import { getServerSession } from "next-auth/next"
import { authOptions } from "@/app/api/auth/[...nextauth]/route"
import Provider from './context/client-provider'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
})
{

  const session = await getServerSession(authOptions)

  return (
    <html lang="en" suppressHydrationWarning >
      
      <html lang="en">
      <Provider session={session}>
      <body className={inter.className}>{children}</body>
      </Provider>
    </html>

  </html>
  )
}
